export const routes = [
  "/",
  "/features",
  "/solutions/restaurants",
  "/solutions/cafes",
  "/solutions/multi-location",
  "/offline-first",
  "/kitchen-display",
  "/inventory",
  "/reports",
  "/hardware",
  "/security",
  "/demo",
  "/docs",
  "/contact",
  "/privacy",
  "/terms",
];
